version: '2'
services:
  data:
    build:
      context: ./www-data
      args:
        - SSH_USER
        - UPLOADED_BY
        - DOMAIN_TLD
        - DOMAIN_TLD_DEV
        - DOMAIN_TLD_BETA
        - DOMAIN_TLD_MIRROR
  conf:
    build:
      context: ./services-conf
      args:
        - SSH_USER
        - SSH_PUBLIC_KEY
        - SSL_CUSTOM_CERT
        - DOMAIN_TLD
        - DOMAIN_TLD_DEV
        - DOMAIN_TLD_BETA
  base:
    build:
      context: ./os-services
      args:
        - SSH_USER
        - SSH_USER_PASS
        - APT_CATCHER_IP
    depends_on:
      - conf
      - data
    ports:
      - "${REPO_HTTP_PORT}:80"
      - "${REPO_HTTPS_PORT}:443"
      - "${REPO_SSH_PORT}:2222"
    volumes_from:
      - conf
      - data
    restart: on-failure:5
    volumes:
      - ~/supervisor_logs:/supervisor_logs
